site_name: llama-cpp-agent
repo_url: https://github.com/Maximilian-Winter/llama-cpp-agent

theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            group_by_category: false
            signature_crossrefs: true
            show_signature: true
            docstring_section_style: list
            show_root_heading: true
            heading_level: 3
            preload_modules:
              - typing
              - typing_extensions
              - ctypes
          import:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv

watch:
  - src/llama_cpp_agent
  - ReadMe.md

nav:
  - "Getting Started": "index.md"
  - "Usage Examples":
      "Simple Chat": "simple-chat-example.md"
      "Function Calling Agent": "function-calling-agent.md"
      "Structured Output Agent": "structured-output-example.md"
      "Knowledge Graph Generation": "knowledge-graph-example.md"


  - "API Reference":
      "Agents API": "agents-api-reference.md"
      "Function Calling API": "function-calling-api-reference.md"
      "Settings API": "settings-api-reference.md"
      "Output Parsing API": "output-parser-api-reference.md"
      "Grammar Generator API": "grammar-api-reference.md"

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: abetlen
      repo: llama-cpp-python
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tilde
  - tables
